this is for  leraning python tools

lerning python numpty

In [5]:
#lerning python numpty

import numpy as np

print("loaded numpy")


loaded numpy


In [3]:
a = np.array([1,2,3])
print(a.shape)
print(a.size)
print(a.ndim)



(3,)
3
1


In [8]:
b = np.array([[0,1,2],[3,4,5]])
print(b.shape)
print(b.size)
print(b.ndim)

(2, 3)
6
2


In [9]:
b = np.array([[0,1],[3,4],[2,5]])
print(b.shape)
print(b.size)
print(b.ndim)

(3, 2)
6
2


In [10]:
c = np.array([[[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]])
print(c.shape)
print(c.size)
print(c.ndim)


(2, 2, 3)
12
3


In [12]:
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b.size)
print(c.ndim)


(2, 3)
6
3


In [19]:
print("looking reshap")
print(b.reshape(6))
print("")
print(b.reshape(3,2))
print("")
print(b.reshape(6,1))
print("some that does not work")
print("b.reshape(6,2)")
print("reshape(row,cols): row * cols need to = b.shape")

looking reshap
[1 2 3 4 5 6]

[[1 2]
 [3 4]
 [5 6]]

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
some that does not work
b.reshape(6,2)
reshape(row,cols): row * cols need to = b.shape
